[platformio]
default_envs = promicro16

[env]
build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wpedantic
    -Wshadow

[env:promicro16]

platform = atmelavr
board = sparkfun_promicro16
framework = arduino
monitor_speed = 115200